import LenisScroll from "./components/Smooth";
import "./globals.css";

import { Outfit, Quicksand } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
     className={`${outfit.variable} ${quicksand.variable}`}
    >
      <body className="min-h-full flex flex-col">{children}
        <LenisScroll/>
      </body>
    </html>
  );
}
